CREATE TABLE [ast].[WlcIpaClmsDaily] (
    [astUrn]            INT           IDENTITY (1, 1) NOT NULL,
    [LastName]          VARCHAR (50)  NULL,
    [FirstName]         VARCHAR (50)  NULL,
    [DOB]               VARCHAR (50)  NULL,
    [SubscriberID]      VARCHAR (50)  NULL,
    [ProviderID]        VARCHAR (50)  NULL,
    [ProviderLastName]  VARCHAR (50)  NULL,
    [ProviderFirstName] VARCHAR (50)  NULL,
    [ProviderAddress]   VARCHAR (100) NULL,
    [CityStateZip]      VARCHAR (100) NULL,
    [PcName]            VARCHAR (50)  NULL,
    [DetailSVCDate]     VARCHAR (50)  NULL,
    [SVCDate]           VARCHAR (50)  NULL,
    [AuthNumber]        VARCHAR (50)  NULL,
    [Procedure]         VARCHAR (50)  NULL,
    [Description]       VARCHAR (255) NULL,
    [Modifier]          VARCHAR (50)  NULL,
    [Quantity]          VARCHAR (50)  NULL,
    [Diagnosis_1]       VARCHAR (50)  NULL,
    [Diagnosis_2]       VARCHAR (50)  NULL,
    [Diagnosis_3]       VARCHAR (50)  NULL,
    [Diagnosis_4]       VARCHAR (50)  NULL,
    [Diagnosis_5]       VARCHAR (50)  NULL,
    [Diagnosis_6]       VARCHAR (50)  NULL,
    [ProfNet]           VARCHAR (50)  NULL,
    [Billed]            VARCHAR (50)  NULL,
    [Allowed]           VARCHAR (50)  NULL,
    [Copay]             VARCHAR (50)  NULL,
    [DRG]               VARCHAR (50)  NULL,
    [Claim]             VARCHAR (50)  NULL,
    [Line#]             VARCHAR (50)  NULL,
    [LCode]             VARCHAR (50)  NULL,
    [POS]               VARCHAR (50)  NULL,
    [Date]              VARCHAR (50)  NULL,
    [ProfInst]          VARCHAR (50)  NULL,
    [Carrier]           VARCHAR (50)  NULL,
    [Reason]            VARCHAR (255) NULL,
    [AltPCode]          VARCHAR (50)  NULL,
    [IPA]               VARCHAR (50)  NULL,
    [TotalBilledAmt]    VARCHAR (50)  NULL,
    [DetailHold]        VARCHAR (50)  NULL,
    [HeaderHold]        VARCHAR (50)  NULL,
    [LoadDate]          DATE          NULL,
    [DataDate]          DATE          NULL,
    [srcFileName]       VARCHAR (100) NULL,
    [CreatedDate]       DATETIME      CONSTRAINT [DF_astWlcIpaClmsDaily_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedBy]         VARCHAR (50)  CONSTRAINT [DF_astWlcIpaClmsDaily_CreatedBy] DEFAULT (suser_sname()) NULL,
    [IsCleaned]         BIT           CONSTRAINT [DF_astWlcIpaClmsDaily_IsCleaned] DEFAULT ((0)) NULL,
    CONSTRAINT [PK__WlcIpaCl__2E81F97E4428C270] PRIMARY KEY CLUSTERED ([astUrn] ASC)
);

