CREATE TABLE [adi].[AetCom_ProvCost_Data] (
    [AetComProvCostDataKey] INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]      VARCHAR (100) NOT NULL,
    [SrcFileName]           VARCHAR (100) NOT NULL,
    [LoadDate]              DATE          NOT NULL,
    [CreatedDate]           DATE          CONSTRAINT [DF_AetCom_ProvCost_Data_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]             VARCHAR (50)  CONSTRAINT [DF_AetCom_ProvCost_Data_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]       DATETIME      CONSTRAINT [DF_AetCom_ProvCost_Data_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]         VARCHAR (50)  CONSTRAINT [DF_AetCom_ProvCost_Data_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ATTR_TAX_ID]           VARCHAR (50)  NULL,
    [ATTR_TAX_ID_NAME]      VARCHAR (50)  NULL,
    [ATTR_PRVDR_ID]         VARCHAR (50)  NULL,
    [ATTR_PRINT_NM]         VARCHAR (50)  NULL,
    [ATTR_ORG_CD]           VARCHAR (50)  NULL,
    [IPFac1_Paid_Amt]       MONEY         NULL,
    [IPFac2a_Paid_Amt]      MONEY         NULL,
    [IPFac2b_Paid_Amt]      MONEY         NULL,
    [IPFac3_Paid_Amt]       MONEY         NULL,
    [IPFac_Paid_Amt]        MONEY         NULL,
    [AMBFac1_Paid_Amt]      MONEY         NULL,
    [AMBFac2a_Paid_Amt]     MONEY         NULL,
    [AMBFac2b_Paid_Amt]     MONEY         NULL,
    [AMBFac3_Paid_Amt]      MONEY         NULL,
    [AMBFac_Paid_Amt]       MONEY         NULL,
    [Emerg1_Paid_Amt]       MONEY         NULL,
    [Emerg2a_Paid_Amt]      MONEY         NULL,
    [Emerg2b_Paid_Amt]      MONEY         NULL,
    [Emerg3_Paid_Amt]       MONEY         NULL,
    [Emerg_Paid_Amt]        MONEY         NULL,
    [SpecPhy1_Paid_Amt]     MONEY         NULL,
    [SpecPhy2a_Paid_Amt]    MONEY         NULL,
    [SpecPhy2b_Paid_Amt]    MONEY         NULL,
    [SpecPhy3_Paid_Amt]     MONEY         NULL,
    [SpecPhy_Paid_Amt]      MONEY         NULL,
    [PCPPhy1_Paid_Amt]      MONEY         NULL,
    [PCPPhy2a_Paid_Amt]     MONEY         NULL,
    [PCPPhy2b_Paid_Amt]     MONEY         NULL,
    [PCPPhy3_Paid_Amt]      MONEY         NULL,
    [PCPPhy_Paid_Amt]       MONEY         NULL,
    [Rad1_Paid_Amt]         MONEY         NULL,
    [Rad2a_Paid_Amt]        MONEY         NULL,
    [Rad2b_Paid_Amt]        MONEY         NULL,
    [Rad3_Paid_Amt]         MONEY         NULL,
    [Rad_Paid_Amt]          MONEY         NULL,
    [Lab1_Paid_Amt]         MONEY         NULL,
    [Lab2a_Paid_Amt]        MONEY         NULL,
    [Lab2b_Paid_Amt]        MONEY         NULL,
    [Lab3_Paid_Amt]         MONEY         NULL,
    [Lab_Paid_Amt]          MONEY         NULL,
    [HomeHealth1_Paid_Amt]  MONEY         NULL,
    [HomeHealth2a_Paid_Amt] MONEY         NULL,
    [HomeHealth2b_Paid_Amt] MONEY         NULL,
    [HomeHealth3_Paid_Amt]  MONEY         NULL,
    [HomeHealth_Paid_Amt]   MONEY         NULL,
    [MentHealth1_Paid_Amt]  MONEY         NULL,
    [MentHealth2a_Paid_Amt] MONEY         NULL,
    [MentHealth2b_Paid_Amt] MONEY         NULL,
    [MentHealth3_Paid_Amt]  MONEY         NULL,
    [MentHealth_Paid_Amt]   MONEY         NULL,
    [MedRx1_Paid_Amt]       MONEY         NULL,
    [MedRx2a_Paid_Amt]      MONEY         NULL,
    [MedRx2b_Paid_Amt]      MONEY         NULL,
    [MedRx3_Paid_Amt]       MONEY         NULL,
    [MedRx_Paid_Amt]        MONEY         NULL,
    [Other1_Paid_Amt]       MONEY         NULL,
    [Other2a_Paid_Amt]      MONEY         NULL,
    [Other2b_Paid_Amt]      MONEY         NULL,
    [Other3_Paid_Amt]       MONEY         NULL,
    [Other_Paid_Amt]        MONEY         NULL,
    [ALL1_Paid_Amt]         MONEY         NULL,
    [ALL2a_Paid_Amt]        MONEY         NULL,
    [ALL2b_Paid_Amt]        MONEY         NULL,
    [ALL3_Paid_Amt]         MONEY         NULL,
    [ALL_Paid_Amt]          MONEY         NULL,
    [IPFac1_Mem_Cnt]        INT           NULL,
    [IPFac2a_Mem_Cnt]       INT           NULL,
    [IPFac2b_Mem_Cnt]       INT           NULL,
    [IPFac3_Mem_Cnt]        INT           NULL,
    [IPFac_Mem_Cnt]         INT           NULL,
    [AMBFac1_Mem_Cnt]       INT           NULL,
    [AMBFac2a_Mem_Cnt]      INT           NULL,
    [AMBFac2b_Mem_Cnt]      INT           NULL,
    [AMBFac3_Mem_Cnt]       INT           NULL,
    [AMBFac_Mem_Cnt]        INT           NULL,
    [Emerg1_Mem_Cnt]        INT           NULL,
    [Emerg2a_Mem_Cnt]       INT           NULL,
    [Emerg2b_Mem_Cnt]       INT           NULL,
    [Emerg3_Mem_Cnt]        INT           NULL,
    [Emerg_Mem_Cnt]         INT           NULL,
    [SpecPhy1_Mem_Cnt]      INT           NULL,
    [SpecPhy2a_Mem_Cnt]     INT           NULL,
    [SpecPhy2b_Mem_Cnt]     INT           NULL,
    [SpecPhy3_Mem_Cnt]      INT           NULL,
    [SpecPhy_Mem_Cnt]       INT           NULL,
    [PCPPhy1_Mem_Cnt]       INT           NULL,
    [PCPPhy2a_Mem_Cnt]      INT           NULL,
    [PCPPhy2b_Mem_Cnt]      INT           NULL,
    [PCPPhy3_Mem_Cnt]       INT           NULL,
    [PCPPhy_Mem_Cnt]        INT           NULL,
    [Rad1_Mem_Cnt]          INT           NULL,
    [Rad2a_Mem_Cnt]         INT           NULL,
    [Rad2b_Mem_Cnt]         INT           NULL,
    [Rad3_Mem_Cnt]          INT           NULL,
    [Rad_Mem_Cnt]           INT           NULL,
    [Lab1_Mem_Cnt]          INT           NULL,
    [Lab2a_Mem_Cnt]         INT           NULL,
    [Lab2b_Mem_Cnt]         INT           NULL,
    [Lab3_Mem_Cnt]          INT           NULL,
    [Lab_Mem_Cnt]           INT           NULL,
    [HomeHealth1_Mem_Cnt]   INT           NULL,
    [HomeHealth2a_Mem_Cnt]  INT           NULL,
    [HomeHealth2b_Mem_Cnt]  INT           NULL,
    [HomeHealth3_Mem_Cntm]  INT           NULL,
    [HomeHealth_Mem_Cnt]    INT           NULL,
    [MentHealth1_Mem_Cnt]   INT           NULL,
    [MentHealth2a_Mem_Cnt]  INT           NULL,
    [MentHealth2b_Mem_Cnt]  INT           NULL,
    [MentHealth3_Mem_Cnt]   INT           NULL,
    [MentHealth_Mem_Cnt]    INT           NULL,
    [MedRx1_Mem_Cnt]        INT           NULL,
    [MedRx2a_Mem_Cnt]       INT           NULL,
    [MedRx2b_Mem_Cnt]       INT           NULL,
    [MedRx3_Mem_Cnt]        INT           NULL,
    [MedRx_Mem_Cnt]         INT           NULL,
    [Other1_Mem_Cnt]        INT           NULL,
    [Other2a_Mem_Cnt]       INT           NULL,
    [Other2b_Mem_Cnt]       INT           NULL,
    [Other3_Mem_Cnt]        INT           NULL,
    [Other_Mem_Cnt]         INT           NULL,
    [ALL1_Mem_Cnt]          INT           NULL,
    [ALL2a_Mem_Cnt]         INT           NULL,
    [ALL2b_Mem_Cnt]         INT           NULL,
    [ALL3_Mem_Cnt]          INT           NULL,
    [ALL_Mem_Cnt]           INT           NULL,
    [Dist_Member_Count]     INT           NULL,
    [Member_Months]         INT           NULL,
    [Avg_Member_Count]      DECIMAL (18)  NULL,
    [Total_Age]             INT           NULL,
    [Total_Retro_Risk]      VARCHAR (50)  NULL,
    [DataDate]              DATE          NULL,
    [FileDate]              DATE          NULL,
    [PCPMiddleName]         VARCHAR (50)  NULL,
    [PCPLastName]           VARCHAR (50)  NULL,
    [PCPName]               VARCHAR (100) NULL,
    [PCP_NPI]               VARCHAR (20)  NULL,
    [Chapter]               VARCHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([AetComProvCostDataKey] ASC)
);

