CREATE TABLE [adi].[AetnaCommGIC_ActionList] (
    [ActionListKey]          INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]       VARCHAR (100) NOT NULL,
    [SrcFileName]            VARCHAR (100) NOT NULL,
    [LoadDate]               DATE          NOT NULL,
    [CreatedDate]            DATE          CONSTRAINT [DF_adiAetnaCommGIC_ActionList_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              VARCHAR (50)  CONSTRAINT [DF_adiAetnaCommGIC_ActionList_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]        DATETIME      CONSTRAINT [DF_adiAetnaCommGIC_ActionList_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]          VARCHAR (50)  CONSTRAINT [DF_adiAetnaCommGIC_ActionList_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [OrgCode]                VARCHAR (20)  NULL,
    [GapCount]               INT           NULL,
    [OnPriorList]            CHAR (1)      NULL,
    [SourceCUMBID]           VARCHAR (50)  NULL,
    [AetnaCardID]            VARCHAR (50)  NULL,
    [SeqNumber]              VARCHAR (20)  NULL,
    [Funding]                VARCHAR (50)  NULL,
    [PlanSponsorName]        VARCHAR (50)  NULL,
    [MemberID]               VARCHAR (50)  NULL,
    [LastName]               VARCHAR (50)  NULL,
    [FirstName]              VARCHAR (50)  NULL,
    [DateBirth]              DATE          NULL,
    [Gender]                 CHAR (1)      NULL,
    [Phone]                  VARCHAR (20)  NULL,
    [SegmentName]            VARCHAR (50)  NULL,
    [Carrier]                VARCHAR (50)  NULL,
    [MemberActive]           VARCHAR (10)  NULL,
    [AttributedTIN]          VARCHAR (20)  NULL,
    [AttributedTIName]       VARCHAR (50)  NULL,
    [AttributedPIN]          VARCHAR (20)  NULL,
    [AttributedProviderNPI]  VARCHAR (20)  NULL,
    [AttributedProviderName] VARCHAR (50)  NULL,
    [LastSeenPCPName]        VARCHAR (50)  NULL,
    [LastseenPCPNPI]         VARCHAR (20)  NULL,
    [LastseenPCPVisitDate]   DATE          NULL,
    [NumberDaysLastPCPvisit] INT           NULL,
    [PCPwithinACO]           VARCHAR (50)  NULL,
    [LastSeenSpecName]       VARCHAR (50)  NULL,
    [LastSeenSpecSpclty]     VARCHAR (50)  NULL,
    [LastseenSpecVisitDate]  DATE          NULL,
    [MedicalConditions]      VARCHAR (50)  NULL,
    [ContinuousEnrollment]   VARCHAR (50)  NULL,
    [Measure]                VARCHAR (50)  NULL,
    [ActionRequired]         VARCHAR (50)  NULL,
    [LastTest_ExamDate]      DATE          NULL,
    [ValueType]              VARCHAR (50)  NULL,
    [Value]                  VARCHAR (50)  NULL,
    [Exam_DrugName]          VARCHAR (50)  NULL,
    [HBA1C_Value]            VARCHAR (50)  NULL,
    [DataDate]               DATE          NULL,
    [RowStatus]              TINYINT       DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([ActionListKey] ASC)
);

