CREATE TABLE [adi].[ClmsAetComTx] (
    [ClmsAetComTxKey]      INT             IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]     VARCHAR (100)   NOT NULL,
    [SrcFileName]          VARCHAR (100)   NOT NULL,
    [LoadDate]             DATE            NOT NULL,
    [CreatedDate]          DATE            CONSTRAINT [DF_adiClmsAetComTx_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]            VARCHAR (50)    CONSTRAINT [DF_adiClmsAetComTx_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]      DATETIME        CONSTRAINT [DF_adiClmsAetComTx_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]        VARCHAR (50)    CONSTRAINT [DF_adiClmsAetComTx_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ps_unique_id]         VARCHAR (16)    NULL,
    [customer_nbr]         VARCHAR (8)     NULL,
    [group_nbr]            VARCHAR (8)     NULL,
    [idn_indicator]        CHAR (3)        NULL,
    [subgroup_nbr]         VARCHAR (8)     NULL,
    [account_nbr]          CHAR (5)        NULL,
    [file_id]              CHAR (2)        NULL,
    [clm_ln_type_cd]       CHAR (1)        NULL,
    [non_prfrrd_srv_cd_1]  CHAR (1)        NULL,
    [plsp_prod_cd]         CHAR (2)        NULL,
    [product_ln_cd]        CHAR (2)        NULL,
    [classification_cd]    CHAR (1)        NULL,
    [bnft_pkg_id]          CHAR (5)        NULL,
    [plan_id]              CHAR (5)        NULL,
    [non_prfrrd_srv_cd_2]  CHAR (1)        NULL,
    [fund_ctg_cd]          CHAR (1)        NULL,
    [src_subscriber_id]    VARCHAR (11)    NULL,
    [emp_last_nm]          VARCHAR (30)    NULL,
    [emp_first_nm]         VARCHAR (30)    NULL,
    [emp_gender]           CHAR (1)        NULL,
    [subscriber_brth_dt]   DATE            NULL,
    [subs_zip_cd]          VARCHAR (5)     NULL,
    [subs_st_postal_cd]    CHAR (2)        NULL,
    [coverage_type_cd]     CHAR (1)        NULL,
    [ssn_nbr]              VARCHAR (11)    NULL,
    [member_id]            VARCHAR (20)    NULL,
    [src_clm_mbr_id]       CHAR (2)        NULL,
    [mem_last_nm]          VARCHAR (30)    NULL,
    [mem_first_nm]         VARCHAR (30)    NULL,
    [mem_gender]           CHAR (1)        NULL,
    [mbr_rtp_type_cd]      CHAR (1)        NULL,
    [birth_dt]             DATE            NULL,
    [src_clm_id]           VARCHAR (19)    NULL,
    [src_claim_line_id_1]  CHAR (2)        NULL,
    [prev_clm_seg_id]      CHAR (2)        NULL,
    [derived_tcn_nbr]      VARCHAR (15)    NULL,
    [src_claim_line_id_2]  CHAR (3)        NULL,
    [claim_line_id]        DECIMAL (12)    NULL,
    [ntwk_srv_area_id]     CHAR (5)        NULL,
    [paid_prvdr_nsa_id]    CHAR (5)        NULL,
    [srv_capacity_cd]      CHAR (1)        NULL,
    [tax_id_format_cd_1]   CHAR (1)        NULL,
    [tax_id_nbr_1]         VARCHAR (9)     NULL,
    [print_nm_1]           VARCHAR (40)    NULL,
    [tax_id_format_cd_2]   CHAR (1)        NULL,
    [tax_id_nbr_2]         VARCHAR (9)     NULL,
    [srv_prvdr_id]         VARCHAR (7)     NULL,
    [print_nm_2]           VARCHAR (40)    NULL,
    [address_line_1_txt]   VARCHAR (35)    NULL,
    [address_line_2_txt]   VARCHAR (35)    NULL,
    [city_nm]              VARCHAR (30)    NULL,
    [state_postal_cd]      CHAR (2)        NULL,
    [zip_cd]               CHAR (5)        NULL,
    [provider_type_cd]     VARCHAR (3)     NULL,
    [specialty_cd]         CHAR (5)        NULL,
    [payee_cd]             CHAR (1)        NULL,
    [paid_prvdr_par_cd]    CHAR (1)        NULL,
    [received_dt]          DATE            NULL,
    [adjn_dt]              DATE            NULL,
    [srv_start_dt]         DATE            NULL,
    [srv_stop_dt]          DATE            NULL,
    [paid_dt_OR_adjn_dt]   DATE            NULL,
    [FILLER_1]             VARCHAR (6)     NULL,
    [FILLER_2]             VARCHAR (6)     NULL,
    [FILLER_3]             VARCHAR (6)     NULL,
    [mdc_cd]               CHAR (2)        NULL,
    [drg_cd]               CHAR (3)        NULL,
    [prcdr_cd]             CHAR (5)        NULL,
    [prcdr_modifier_cd_1]  CHAR (2)        NULL,
    [prcdr_type_cd]        CHAR (1)        NULL,
    [ICD10_Indicator]      CHAR (5)        NULL,
    [MED_COST_SUBCTG_CD]   CHAR (5)        NULL,
    [prcdr_group_nbr]      CHAR (5)        NULL,
    [type_srv_cd]          CHAR (2)        NULL,
    [srv_benefit_cd]       CHAR (3)        NULL,
    [tooth_1_nbr]          CHAR (5)        NULL,
    [plc_srv_cd]           CHAR (2)        NULL,
    [dschrg_status_cd]     CHAR (2)        NULL,
    [revenue_cd]           CHAR (4)        NULL,
    [hcfa_bill_type_cd]    CHAR (3)        NULL,
    [unit_cnt]             DECIMAL (10, 2) NULL,
    [src_unit_cnt]         DECIMAL (12, 2) NULL,
    [src_billed_amt]       DECIMAL (10, 2) NULL,
    [billed_amt]           DECIMAL (10, 2) NULL,
    [not_covered_amt_1]    DECIMAL (10, 2) NULL,
    [not_covered_amt_2]    DECIMAL (10, 2) NULL,
    [not_covered_amt_3]    DECIMAL (10, 2) NULL,
    [clm_ln_msg_cd_1]      CHAR (4)        NULL,
    [clm_ln_msg_cd_2]      CHAR (4)        NULL,
    [clm_ln_msg_cd_3]      CHAR (4)        NULL,
    [covered_amt]          DECIMAL (10, 2) NULL,
    [allowed_amt]          DECIMAL (10, 2) NULL,
    [ReservedForFutureUse] VARCHAR (10)    NULL,
    [srv_copay_amt]        DECIMAL (10, 2) NULL,
    [src_srv_copay_amt]    DECIMAL (10, 2) NULL,
    [deductible_amt]       DECIMAL (10, 2) NULL,
    [coinsurance_amt]      DECIMAL (10, 2) NULL,
    [src_coins_amt]        DECIMAL (10, 2) NULL,
    [bnft_payable_amt]     DECIMAL (10, 2) NULL,
    [paid_amt]             DECIMAL (10, 2) NULL,
    [cob_paid_amt]         DECIMAL (10, 2) NULL,
    [ahf_bfd_amt]          DECIMAL (10, 2) NULL,
    [ahf_paid_amt]         DECIMAL (10, 2) NULL,
    [negot_savings_amt]    DECIMAL (10, 2) NULL,
    [r_c_savings_amt]      DECIMAL (10, 2) NULL,
    [cob_savings_amt]      DECIMAL (10, 2) NULL,
    [src_cob_svngs_amt]    DECIMAL (10, 2) NULL,
    [pri_payer_cvg_cd]     CHAR (1)        NULL,
    [cob_type_cd]          CHAR (1)        NULL,
    [cob_cd]               CHAR (1)        NULL,
    [prcdr_cd_ndc]         VARCHAR (11)    NULL,
    [src_clm_mbr_id_2]     VARCHAR (22)    NULL,
    [clm_ln_status_cd]     CHAR (1)        NULL,
    [src_member_id]        VARCHAR (22)    NULL,
    [reversal_cd]          CHAR (2)        NULL,
    [admit_cnt]            CHAR (2)        NULL,
    [admin_savings_amt]    DECIMAL (10, 2) NULL,
    [adj_prvdr_dsgnn_cd]   CHAR (3)        NULL,
    [aex_plan_dsgntn_cd]   CHAR (1)        NULL,
    [benefit_tier_cd]      CHAR (2)        NULL,
    [aex_prvdr_spctg_cd]   CHAR (4)        NULL,
    [prod_distnctn_cd]     CHAR (1)        NULL,
    [billed_eligible_amt]  DECIMAL (10, 2) NULL,
    [SPCLTY_CTG_CLS_CD]    CHAR (3)        NULL,
    [poa_cd_1]             CHAR (1)        NULL,
    [poa_cd_2]             CHAR (1)        NULL,
    [poa_cd_3]             CHAR (1)        NULL,
    [FILLER_4]             CHAR (6)        NULL,
    [FILLER_5]             VARCHAR (6)     NULL,
    [FILLER_6]             VARCHAR (6)     NULL,
    [pricing_mthd_cd]      CHAR (1)        NULL,
    [type_class_cd]        CHAR (1)        NULL,
    [specialty_ctg_cd]     CHAR (4)        NULL,
    [srv_prvdr_npi]        VARCHAR (20)    NULL,
    [ttl_ded_met_ind]      CHAR (1)        NULL,
    [ttl_interest_amt]     DECIMAL (10)    NULL,
    [ttl_surcharge_amt]    DECIMAL (10)    NULL,
    [SRV_SPCLTY_CTG_CD]    CHAR (4)        NULL,
    [HCFA_PLC_SRV_CD]      CHAR (2)        NULL,
    [HCFA_ADMIT_SRC_CD]    CHAR (1)        NULL,
    [HCFA_ADMIT_TYPE_CD_1] CHAR (1)        NULL,
    [SRC_ADMIT_DT]         DATE            NULL,
    [SRC_DISCHARGE_DT]     DATE            NULL,
    [prcdr_modifier_cd_2]  CHAR (2)        NULL,
    [prcdr_modifier_cd_3]  CHAR (2)        NULL,
    [poa_cd_4]             CHAR (1)        NULL,
    [poa_cd_5]             CHAR (1)        NULL,
    [poa_cd_6]             CHAR (1)        NULL,
    [poa_cd_7]             CHAR (1)        NULL,
    [poa_cd_8]             CHAR (1)        NULL,
    [poa_cd_9]             CHAR (1)        NULL,
    [poa_cd_10]            CHAR (1)        NULL,
    [pri_icd9_dx_cd]       VARCHAR (8)     NULL,
    [icd9_dx_cd_2]         VARCHAR (8)     NULL,
    [icd9_dx_cd_3]         VARCHAR (8)     NULL,
    [icd9_dx_cd_4]         VARCHAR (8)     NULL,
    [icd9_dx_cd_5]         VARCHAR (8)     NULL,
    [icd9_dx_cd_6]         VARCHAR (8)     NULL,
    [icd9_dx_cd_7]         VARCHAR (8)     NULL,
    [icd9_dx_cd_8]         VARCHAR (8)     NULL,
    [icd9_dx_cd_9]         VARCHAR (8)     NULL,
    [icd9_dx_cd_10]        VARCHAR (8)     NULL,
    [icd9_prcdr_cd1]       VARCHAR (7)     NULL,
    [icd9_prcdr_cd2]       VARCHAR (7)     NULL,
    [icd9_prcdr_cd3]       VARCHAR (7)     NULL,
    [icd9_prcdr_cd4]       VARCHAR (7)     NULL,
    [icd9_prcdr_cd5]       VARCHAR (7)     NULL,
    [icd9_prcdr_cd6]       VARCHAR (7)     NULL,
    [ahf_det_order_cd]     CHAR (3)        NULL,
    [ahf_mbr_coins_amt]    DECIMAL (10, 2) NULL,
    [ahf_mbr_copay_amt]    DECIMAL (10, 2) NULL,
    [ahf_mbr_ded_amt]      DECIMAL (10, 2) NULL,
    [SensitivityIndicator] CHAR (1)        NULL,
    [hcfa_admit_type_cd_2] CHAR (1)        NULL,
    [FILLER_7]             VARCHAR (20)    NULL,
    [ORG_CD]               VARCHAR (10)    NULL,
    [valueX]               CHAR (1)        NULL,
    [Datadate]             DATE            NULL,
    PRIMARY KEY CLUSTERED ([ClmsAetComTxKey] ASC)
);


GO


CREATE TRIGGER [adi].[TR_adiClmsAetComTx]
    ON adi.ClmsAetComTx
    FOR UPDATE
    AS
    BEGIN
	   IF @@rowcount = 0 
		RETURN
        SET NoCount ON
	   if exists(SELECT * FROM inserted)
		  UPDATE adi.ClmsAetComTx
			 SET LastUpdatedDate = GETDATE()
    				,LastUpdatedBy  = system_user
	   	  FROM inserted i, ClmsAetComTx a
		  WHERE i.ClmsAetComTxKey = a.ClmsAetComTxKey
    END
