CREATE TABLE [lst].[LIST_NPPES_NPI] (
    [LstNppesNPIKey]     INT           IDENTITY (1, 1) NOT NULL,
    [srcFileName]        VARCHAR (100) DEFAULT ('AceMasterData.[lst].[LIST_NPPES_NPI]') NOT NULL,
    [DataDate]           DATE          NOT NULL,
    [CreatedDate]        DATETIME      DEFAULT (getdate()) NOT NULL,
    [CreatedBy]          VARCHAR (50)  DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]    DATETIME      DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]      VARCHAR (50)  DEFAULT (suser_sname()) NOT NULL,
    [NPI]                VARCHAR (20)  NOT NULL,
    [EntityType]         VARCHAR (20)  NULL,
    [EIN]                VARCHAR (50)  NULL,
    [LBN]                VARCHAR (100) NULL,
    [LBN_Name]           VARCHAR (200) NULL,
    [LastName]           VARCHAR (100) NULL,
    [FirstName]          VARCHAR (100) NULL,
    [PracticeAddress1]   VARCHAR (100) NULL,
    [PracticeAddress2]   VARCHAR (50)  NULL,
    [PracticeCity]       VARCHAR (100) NULL,
    [PracticeState]      VARCHAR (50)  NULL,
    [PracticeZip]        VARCHAR (10)  NULL,
    [PracticePhone]      VARCHAR (20)  NULL,
    [PracticeFax]        VARCHAR (20)  NULL,
    [PracticeLastUpdate] VARCHAR (20)  NULL,
    [Taxonomy1]          VARCHAR (50)  NULL,
    [Taxonomy2]          VARCHAR (50)  NULL,
    [Taxonomy3]          VARCHAR (50)  NULL,
    [Active]             CHAR (1)      DEFAULT ('Y') NULL,
    [EffectiveDate]      DATE          DEFAULT (getdate()) NULL,
    [ExpirationDate]     DATE          NULL,
    [Status]             VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([LstNppesNPIKey] ASC)
);

