CREATE TABLE [adw].[tmp_Active_Members] (
    [URN]            INT           IDENTITY (1, 1) NOT NULL,
    [MBI]            VARCHAR (50)  NULL,
    [HICN]           VARCHAR (50)  NOT NULL,
    [Plan]           VARCHAR (50)  NULL,
    [SubPlan]        VARCHAR (100) NULL,
    [FirstName]      VARCHAR (50)  NULL,
    [LastName]       VARCHAR (50)  NULL,
    [Sex]            VARCHAR (1)   NULL,
    [DOB]            DATE          NULL,
    [DOD]            DATE          NULL,
    [Exclusion]      VARCHAR (1)   DEFAULT ('N') NULL,
    [Mbr_Type]       VARCHAR (1)   NULL,
    [AWV]            INT           DEFAULT ((0)) NULL,
    [PCP]            INT           DEFAULT ((0)) NULL,
    [IP]             INT           DEFAULT ((0)) NULL,
    [ER]             INT           DEFAULT ((0)) NULL,
    [RA]             INT           DEFAULT ((0)) NULL,
    [CurrentGaps]    INT           DEFAULT ((0)) NULL,
    [HospiceCode]    INT           DEFAULT ((0)) NULL,
    [PCP_Last18Mths] INT           DEFAULT ((0)) NULL,
    [PCP_Last12Mths] INT           DEFAULT ((0)) NULL,
    [AHRGaps]        INT           DEFAULT ((0)) NULL,
    [TIN]            VARCHAR (50)  NULL,
    [TIN_NAME]       VARCHAR (50)  NULL,
    [NPI]            VARCHAR (50)  NULL,
    [NPI_NAME]       VARCHAR (50)  NULL,
    [MBR_YEAR]       INT           NULL,
    [MBR_QTR]        INT           NULL,
    [LOAD_DATE]      DATE          DEFAULT (sysdatetime()) NULL,
    [LOAD_USER]      VARCHAR (50)  DEFAULT (suser_sname()) NULL
);

